name: Build

on:
    push:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            variant: [minimal, full]
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  target: ${{ matrix.variant }}
                  tags: chaptersevenseeds/truenas-jobs-caldav-sync:latest-${{ matrix.variant }}
                  file: ./Dockerfile
